spring:
  application:
    name: journalEntry
  mail:
    host : smtp.gmail.com
    port: 587
    username: akshay***@gmail.com
    password: **
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: ${MONGO_URI}


weather:
  api:
    key: ${WEATHER_API}